import org.gradle.internal.os.OperatingSystem


plugins {
    id "fabric-loom"
    id "legacy-looming" version "1.8-SNAPSHOT"
    id "maven-publish"
}


def getCheckedOutGitCommitHash(Project mcefParent) {
    def gitFolder = "$mcefParent.projectDir/.git/modules/java-cef/"
    def takeFromHash = 40
    /*
     * '.git/HEAD' contains either
     *      in case of detached head: the currently checked out commit hash
     *      otherwise: a reference to a file containing the current commit hash
     */
    def gitHeadFile = new File(gitFolder + "HEAD");
    if (gitHeadFile.exists()) {
        def head = gitHeadFile.text.split(":") // .git/HEAD
        def isCommit = head.length == 1 // e5a7c79edabbf7dd39888442df081b1c9d8e88fd
        // def isRef = head.length > 1     // ref: refs/heads/master

        if (isCommit) return head[0].trim().take(takeFromHash) // e5a7c79edabb

        def refHead = new File(gitFolder + head[1].trim()) // .git/refs/heads/master
        refHead.text.trim().take takeFromHash
    } else {
        return ""
    }
}

tasks.register('cloneJcef', Exec) {
    commandLine 'git', 'submodule', 'update', '--init', '--recursive', 'java-cef'
}

tasks.register('generateJcefCommitFile') {
    doLast {
        def commitHash = getCheckedOutGitCommitHash(project)
        if (!commitHash.isEmpty()) {
            file("$buildDir/jcef.commit").text = commitHash
        } else {
            throw new GradleException("Unable to determine JCEF commit hash.")
        }
    }
}


base.archivesName = project.archives_base_name
version = project.mod_version
group = project.maven_group

switch (OperatingSystem.current()) {
    case OperatingSystem.LINUX:
        project.ext.lwjglNatives = "natives-linux"
        def osArch = System.getProperty("os.arch")
        if (osArch.startsWith("arm") || osArch.startsWith("aarch64")) {
            project.ext.lwjglNatives += osArch.contains("64") || osArch.startsWith("armv8") ? "-arm64" : "-arm32"
        } else if  (osArch.startsWith("ppc")) {
            project.ext.lwjglNatives += "-ppc64le"
        } else if  (osArch.startsWith("riscv")) {
            project.ext.lwjglNatives += "-riscv64"
        }
        break
    case OperatingSystem.MAC_OS:
        project.ext.lwjglNatives = System.getProperty("os.arch").startsWith("aarch64") ? "natives-macos-arm64" : "natives-macos"
        break
    case OperatingSystem.WINDOWS:
        def osArch = System.getProperty("os.arch")
        project.ext.lwjglNatives = osArch.contains("64")
                ? "natives-windows${osArch.startsWith("aarch64") ? "-arm64" : ""}"
                : "natives-windows-x86"
        break
}


repositories {
    maven { url = "https://pkgs.dev.azure.com/djtheredstoner/DevAuth/_packaging/public/maven/v1" }

    maven { url "https://jitpack.io" }
    mavenCentral()
}

loom {
    accessWidenerPath = file("src/main/resources/fabric.accessWidener")

    runs{
        client{
            vmArgs("-XstartOnFirstThread")
        }

    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings(legacy.yarn(project.minecraft_version, project.yarn_build))
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    modImplementation "net.legacyfabric.legacy-fabric-api:legacy-fabric-api:${project.fabric_version}"

    modRuntimeOnly(fileTree("./modImpl/"))


    compileOnly(group: "org.projectlombok", name: "lombok", version: "1.18.24")
    annotationProcessor(group: "org.projectlombok", name: "lombok", version: "1.18.24")

    //Modified version of lwjgl-legacy with some fixes for macos
    implementation(fileTree("./run/mods/lwjgl-legacy-189-1.0.0-all.jar"))

    implementation platform("org.lwjgl:lwjgl-bom:3.3.6")

    runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-nanovg::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-assimp::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-openal::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-opengl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-stb::$lwjglNatives"


    compileOnly("org.projectlombok:lombok:1.18.24")
    annotationProcessor("org.projectlombok:lombok:1.18.24")

    modImplementation("me.djtheredstoner:DevAuth-fabric:1.2.0")


    implementation group: 'org.joml', name: 'joml', version: '1.9.2'



    implementation("javax.vecmath:vecmath:1.5.2")
    compileOnly(fileTree("./run/mods/fabric-example-mod-1.0.0.jar"))



    implementation "com.squareup.okhttp3:okhttp:5.0.0-alpha.14"

}

sourceSets {
    jcef {
        java {
            srcDir "java-cef/java"
            exclude "**/tests/**"
        }
    }

    main {
        compileClasspath += jcef.output
        runtimeClasspath += jcef.output
    }
}


processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }

    dependsOn processJcefResources
    dependsOn generateJcefCommitFile
}


configurations.all {
    exclude group: "org.lwjgl.lwjgl"
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"

    if (JavaVersion.current().isJava9Compatible()) {
        it.options.release = 17
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17

    withSourcesJar()
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(['Specification-Title'     : archives_base_name,
                    'Specification-Vendor'    : group,
                    'Specification-Version'   : "1",
                    'Implementation-Title'    : archives_base_name,
                    'Implementation-Version'  : mod_version,
                    'Implementation-Vendor'   : group,
                    'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
                    'java-cef-commit'         : getCheckedOutGitCommitHash(project)
        ])
    }
    from sourceSets.jcef.output.classesDirs
    from sourceSets.jcef.output.resourcesDir
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
    from("$buildDir/jcef.commit")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {

    }
}